# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for the script (optional, but recommended)
        run: chmod +x ./dep.sh
      - name: Run the shell script
        run: ./dep.sh
      - name: List files in the repository root
        run: ls -R # Lists files recursively from the current director      
      - uses: actions/checkout@v4
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-file
        
